language: node_js
node_js:
- '6'
before_script:
- npm run build
deploy:
  provider: npm
  email: i@vilic.info
  api_key:
    secure: lERl8pjm49lPc1b3rQi+Elo2n3aup/nHXOGITs6RTe9PCP8JE+J2nw1hk0ColuRzXdbaQEfT3ICg47T6FYoxQFpDv0bRZlAOWNFtyiAqIkSRGAbPgUjEozzNx2FQG2BlAOl5DR7tCmEl5Vco0tWuSasQxB17e7+UqB9DO4pqShueYML6VNd5UU0scdr09J+txqeTifY1/1SkkHaVPP7YDWUsRqMBd5X7igYXoacs8SO0H10yzIZ/woe/YmpsNhAgsZ1dMfZ2jy3opPtmabIPmNmAqL3VJ6MUcd9WVLdbD6jRAiG4PZeUciRkaEOPyPjk7PwCu308dBBybu4CyUfZ637ImNELab1pv8QbuJtQoX4eulZiQUlmHeunRTs2CCAE/WeslOWuCDCy3zBt+LTwn0s3MXUKxOEes5iGh78uvqZQrQRCHZeeluT4Ox4MKGuyQLCzbcXpjeDBMyoGl060si9MFPWWn3DybPY0KKtzLT1UhtyF34Hk6hfCMacSdKSIyJY0IQisBEXgshv94J3ARLDJnH+9KByLTLZ+ODHOO6KB1LIrfRAcQaIxRyfIQteryDgJnk+kFZuuESQH/F9WoU/6CSW+01BYpafPyxwg0r9fL8xSznwyCYjItOq+j+K0Kpu28WvrGA60iD5NZ9qsOwdoV756w/BUSoKKJvM85+o=
  on:
    tags: true
    node: '6'
  skip_cleanup: true
